// Generated by tools/tft/fontlooks.py from the stock 1.3.11 screen image: do not edit.
// Per screen font: the Windows font that draws closest to it (CSS family, weight, stretch; GDI family, bold),
// its size in px, horizontal scale, baseline (px from the top of the line) and how far the letters sit
// from their cell centre. Null = no match (no letters or digits): drawn the old way.
namespace User.FXProRpmSync
{
    public static class FontLooks
    {
        public sealed class Look { public string Css, Gdi; public int Weight, Size, Baseline; public string Stretch; public bool Bold; public double Sx, Dx; }
        private static Look L(string css, int weight, string stretch, string gdi, bool bold, int size, double sx, int baseline, double dx) =>
            new Look { Css = css, Weight = weight, Stretch = stretch, Gdi = gdi, Bold = bold, Size = size, Sx = sx, Baseline = baseline, Dx = dx };
        public static readonly Look[] Fonts =
        {
            L("Arial", 700, "normal", "Arial", true, 59, 1.349, 43, -0.44),   // 0 Arial Bold, overlap 0.60
            L("Arial", 700, "normal", "Arial", true, 158, 1.36, 116, -0.31),   // 1 Arial Bold, overlap 0.60
            L("Arial", 700, "normal", "Arial", true, 29, 1.327, 21, -0.44),   // 2 Arial Bold, overlap 0.62
            L("Arial", 700, "normal", "Arial", true, 51, 1.321, 37, -0.6),   // 3 Arial Bold, overlap 0.60
            L("Tahoma", 700, "normal", "Tahoma", true, 32, 1.299, 24, -0.62),   // 4 Tahoma Bold, overlap 0.61
            L("Arial", 700, "normal", "Arial", true, 25, 1.321, 18, -0.4),   // 5 Arial Bold, overlap 0.61
            L("Arial", 700, "normal", "Arial", true, 37, 1.347, 27, -0.65),   // 6 Arial Bold, overlap 0.62
            L("Tahoma", 700, "normal", "Tahoma", true, 29, 1.372, 22, -0.33),   // 7 Tahoma Bold, overlap 0.61
            L("Arial", 700, "normal", "Arial", true, 41, 1.376, 30, -0.35),   // 8 Arial Bold, overlap 0.61
            L("Arial", 700, "normal", "Arial", true, 40, 1.344, 41, -0.21),   // 9 Arial Bold, overlap 0.59
            L("Calibri", 700, "normal", "Calibri", true, 17, 1.501, 11, -0.13),   // 10 Calibri Bold, overlap 0.62
            L("Arial", 700, "normal", "Arial", true, 135, 1.352, 99, -0.27),   // 11 Arial Bold, overlap 0.60
            L("Calibri", 700, "normal", "Calibri", true, 17, 1.501, 11, -0.13),   // 12 Calibri Bold, overlap 0.62
            L("Arial", 700, "normal", "Arial", true, 37, 1.347, 27, -0.65),   // 13 Arial Bold, overlap 0.62
            L("Tahoma", 700, "normal", "Tahoma", true, 20, 1.301, 15, -0.33),   // 14 Tahoma Bold, overlap 0.62
            L("Arial", 700, "normal", "Arial", true, 45, 1.378, 33, -0.4),   // 15 Arial Bold, overlap 0.61
            null,   // 16
            null,   // 17
            L("Arial", 700, "normal", "Arial", true, 184, 0.689, 175, -0.25),   // 18 Arial Bold, overlap 0.69
            L("Arial", 700, "normal", "Arial", true, 78, 0.703, 74, -0.21),   // 19 Arial Bold, overlap 0.70
            L("Arial", 700, "normal", "Arial", true, 83, 0.702, 79, -0.46),   // 20 Arial Bold, overlap 0.71
            L("Arial", 700, "normal", "Arial", true, 63, 0.695, 59, -0.27),   // 21 Arial Bold, overlap 0.72
            L("Arial", 700, "normal", "Arial", true, 33, 0.724, 32, -0.33),   // 22 Arial Bold, overlap 0.73
            L("Arial", 700, "normal", "Arial", true, 70, 0.685, 66, -0.65),   // 23 Arial Bold, overlap 0.72
            null,   // 24
            L("Arial", 400, "normal", "Arial", false, 41, 0.853, 38, -0.5),   // 25 Arial, overlap 0.60
            L("Tahoma", 400, "normal", "Tahoma", false, 174, 0.865, 146, 0.88),   // 26 Tahoma, overlap 0.59
            L("Bahnschrift", 600, "condensed", "Bahnschrift SemiBold Condensed", false, 45, 0.861, 37, -0.31),   // 27 Bahnschrift SemiBold Condensed, overlap 0.71
            null,   // 28
            L("Arial", 700, "normal", "Arial", true, 56, 0.742, 51, -0.15),   // 29 Arial Bold, overlap 0.72
            L("Calibri", 700, "normal", "Calibri", true, 240, 1.046, 165, 0.71),   // 30 Calibri Bold, overlap 0.48
            L("Tahoma", 400, "normal", "Tahoma", false, 58, 1.116, 46, -0.15),   // 31 Tahoma, overlap 0.47
            null,   // 32
            L("Tahoma", 700, "normal", "Tahoma", true, 41, 1.016, 41, -0.17),   // 33 Tahoma Bold, overlap 0.66
            L("Bahnschrift", 700, "condensed", "Bahnschrift Bold Condensed", false, 190, 0.947, 154, 0.08),   // 34 Bahnschrift Bold Condensed, overlap 0.70
            L("Bahnschrift", 300, "condensed", "Bahnschrift Light Condensed", false, 100, 0.817, 81, 0.25),   // 35 Bahnschrift Light Condensed, overlap 0.57
            L("Bahnschrift", 300, "condensed", "Bahnschrift Light Condensed", false, 71, 0.811, 58, -0.55),   // 36 Bahnschrift Light Condensed, overlap 0.58
            null,   // 37
            L("Verdana", 700, "normal", "Verdana", true, 92, 1.792, 87, 0.71),   // 38 Verdana Bold, overlap 0.50
            L("Arial", 400, "normal", "Arial", false, 197, 0.818, 181, -0.42),   // 39 Arial, overlap 0.56
            null,   // 40
            null,   // 41
            L("\"Segoe UI Semibold\"", 600, "normal", "Segoe UI Semibold", false, 258, 0.772, 206, 0.33),   // 42 Segoe UI Semibold, overlap 0.47
            L("Impact", 400, "normal", "Impact", false, 44, 1.153, 53, -2.15),   // 43 Impact, overlap 0.54
            L("Tahoma", 700, "normal", "Tahoma", true, 36, 0.821, 39, -1.52),   // 44 Tahoma Bold, overlap 0.55
            L("Impact", 400, "normal", "Impact", false, 193, 1.678, 193, 0.21),   // 45 Impact, overlap 0.57
            L("Tahoma", 400, "normal", "Tahoma", false, 51, 0.861, 56, -0.13),   // 46 Tahoma, overlap 0.57
            L("Tahoma", 400, "normal", "Tahoma", false, 79, 0.874, 88, -0.1),   // 47 Tahoma, overlap 0.60
            L("Tahoma", 400, "normal", "Tahoma", false, 57, 0.869, 63, -0.02),   // 48 Tahoma, overlap 0.60
            L("Tahoma", 400, "normal", "Tahoma", false, 44, 0.9, 49, -0.17),   // 49 Tahoma, overlap 0.61
            L("Tahoma", 400, "normal", "Tahoma", false, 33, 0.908, 37, -0.02),   // 50 Tahoma, overlap 0.59
            null,   // 51
            L("Tahoma", 400, "normal", "Tahoma", false, 166, 0.865, 186, 0.92),   // 52 Tahoma, overlap 0.60
            L("Tahoma", 400, "normal", "Tahoma", false, 40, 0.91, 45, -0.06),   // 53 Tahoma, overlap 0.62
            L("\"Segoe UI Semibold\"", 600, "normal", "Segoe UI Semibold", false, 46, 0.858, 51, -0.23),   // 54 Segoe UI Semibold, overlap 0.66
            L("\"Segoe UI Semibold\"", 600, "normal", "Segoe UI Semibold", false, 36, 0.844, 38, -0.06),   // 55 Segoe UI Semibold, overlap 0.65
            L("Arial", 400, "normal", "Arial", false, 172, 0.812, 158, -0.46),   // 56 Arial, overlap 0.55
            L("Arial", 400, "normal", "Arial", false, 113, 0.825, 105, -0.6),   // 57 Arial, overlap 0.57
            L("Verdana", 700, "normal", "Verdana", true, 70, 0.55, 57, -0.2),   // 58 Verdana Bold, overlap 0.77
            L("Tahoma", 700, "normal", "Tahoma", true, 33, 1.025, 33, -0.37),   // 59 Tahoma Bold, overlap 0.65
            L("Tahoma", 400, "normal", "Tahoma", false, 24, 1.218, 20, -0.17),   // 60 Tahoma, overlap 0.53
            L("Impact", 400, "normal", "Impact", false, 112, 1.428, 123, 0.54),   // 61 Impact, overlap 0.65
            null,   // 62
            L("Impact", 400, "normal", "Impact", false, 38, 1.193, 42, 0.13),   // 63 Impact, overlap 0.61
            L("Tahoma", 700, "normal", "Tahoma", true, 36, 0.843, 36, -0.23),   // 64 Tahoma Bold, overlap 0.63
            L("Impact", 400, "normal", "Impact", false, 99, 1.249, 109, 0.29),   // 65 Impact, overlap 0.65
            L("Impact", 400, "normal", "Impact", false, 111, 1.237, 121, 0.5),   // 66 Impact, overlap 0.64
            L("Impact", 400, "normal", "Impact", false, 28, 1.167, 30, -0.17),   // 67 Impact, overlap 0.60
            L("Tahoma", 400, "normal", "Tahoma", false, 48, 0.95, 48, -0.15),   // 68 Tahoma, overlap 0.49
            L("Arial", 400, "normal", "Arial", false, 48, 0.718, 45, -0.17),   // 69 Arial, overlap 0.61
            L("Arial", 400, "normal", "Arial", false, 177, 0.697, 167, 0.02),   // 70 Arial, overlap 0.56
            L("Arial", 400, "normal", "Arial", false, 34, 0.72, 32, -0.1),   // 71 Arial, overlap 0.62
            L("Arial", 400, "normal", "Arial", false, 142, 0.666, 131, -0.88),   // 72 Arial, overlap 0.56
            L("Consolas", 700, "normal", "Consolas", true, 50, 0.825, 46, 0.12),   // 73 Consolas Bold, overlap 0.69
            L("Consolas", 700, "normal", "Consolas", true, 63, 0.836, 59, -0.02),   // 74 Consolas Bold, overlap 0.68
            L("Calibri", 700, "normal", "Calibri", true, 218, 0.866, 202, 1.25),   // 75 Calibri Bold, overlap 0.72
            L("Tahoma", 700, "normal", "Tahoma", true, 46, 0.776, 49, -0.21),   // 76 Tahoma Bold, overlap 0.74
            L("Tahoma", 700, "normal", "Tahoma", true, 138, 0.741, 147, -0.08),   // 77 Tahoma Bold, overlap 0.74
            L("Arial", 400, "normal", "Arial", false, 213, 0.819, 196, -0.5),   // 78 Arial, overlap 0.56
            L("Arial", 400, "normal", "Arial", false, 64, 0.841, 59, -0.27),   // 79 Arial, overlap 0.54
            L("Tahoma", 400, "normal", "Tahoma", false, 53, 0.868, 57, -0.1),   // 80 Tahoma, overlap 0.55
            L("Tahoma", 400, "normal", "Tahoma", false, 36, 0.865, 38, -0.25),   // 81 Tahoma, overlap 0.56
            L("Tahoma", 400, "normal", "Tahoma", false, 70, 0.881, 76, -0.02),   // 82 Tahoma, overlap 0.53
            L("Tahoma", 400, "normal", "Tahoma", false, 50, 0.817, 51, 0.04),   // 83 Tahoma, overlap 0.53
            L("Impact", 400, "normal", "Impact", false, 115, 1.026, 126, -0.54),   // 84 Impact, overlap 0.56
            L("Impact", 400, "normal", "Impact", false, 170, 1.334, 188, 13.64),   // 85 Impact, overlap 0.60
            L("Impact", 400, "normal", "Impact", false, 37, 1.379, 42, 2.65),   // 86 Impact, overlap 0.60
            L("Tahoma", 700, "normal", "Tahoma", true, 28, 1.045, 29, 1.62),   // 87 Tahoma Bold, overlap 0.63
            L("Tahoma", 700, "normal", "Tahoma", true, 38, 1.068, 41, 2.62),   // 88 Tahoma Bold, overlap 0.62
            L("Tahoma", 700, "normal", "Tahoma", true, 45, 1.029, 47, 3.17),   // 89 Tahoma Bold, overlap 0.63
            L("Tahoma", 700, "normal", "Tahoma", true, 55, 1.058, 59, 3.88),   // 90 Tahoma Bold, overlap 0.62
            L("Tahoma", 700, "normal", "Tahoma", true, 50, 1.041, 53, 3.54),   // 91 Tahoma Bold, overlap 0.62
            L("Arial", 400, "normal", "Arial", false, 63, 0.829, 57, -0.23),   // 92 Arial, overlap 0.55
            L("Arial", 400, "normal", "Arial", false, 57, 0.825, 53, -0.42),   // 93 Arial, overlap 0.53
            L("Arial", 700, "normal", "Arial", true, 27, 0.752, 25, -0.1),   // 94 Arial Bold, overlap 0.72
            L("Arial", 400, "normal", "Arial", false, 113, 0.851, 105, 0.25),   // 95 Arial, overlap 0.56
            L("Arial", 400, "normal", "Arial", false, 37, 0.861, 35, -0.44),   // 96 Arial, overlap 0.58
            L("Arial", 400, "normal", "Arial", false, 40, 0.846, 37, -0.31),   // 97 Arial, overlap 0.62
            L("Arial", 400, "normal", "Arial", false, 34, 0.865, 32, -0.19),   // 98 Arial, overlap 0.60
            L("Arial", 400, "normal", "Arial", false, 53, 0.892, 51, -0.44),   // 99 Arial, overlap 0.54
            L("Arial", 400, "normal", "Arial", false, 44, 0.846, 40, -0.23),   // 100 Arial, overlap 0.61
            L("Arial", 400, "normal", "Arial", false, 27, 0.875, 26, -0.35),   // 101 Arial, overlap 0.54
            L("Arial", 400, "normal", "Arial", false, 113, 0.83, 105, -0.17),   // 102 Arial, overlap 0.55
            L("Arial", 400, "normal", "Arial", false, 149, 0.821, 123, -0.5),   // 103 Arial, overlap 0.55
            L("Arial", 400, "normal", "Arial", false, 61, 0.84, 56, -0.17),   // 104 Arial, overlap 0.53
            L("Arial", 400, "normal", "Arial", false, 48, 0.859, 45, -0.4),   // 105 Arial, overlap 0.55
            L("Arial", 400, "normal", "Arial", false, 48, 0.846, 43, -0.06),   // 106 Arial, overlap 0.56
            L("\"Franklin Gothic Medium\"", 400, "normal", "Franklin Gothic Medium", false, 22, 0.746, 19, -0.15),   // 107 Franklin Gothic, overlap 0.59
            L("Arial", 400, "normal", "Arial", false, 78, 0.89, 76, 0.04),   // 108 Arial, overlap 0.44
            L("Impact", 400, "normal", "Impact", false, 127, 1.183, 113, -0.25),   // 109 Impact, overlap 0.28
            L("Tahoma", 700, "normal", "Tahoma", true, 34, 1.048, 36, 2.31),   // 110 Tahoma Bold, overlap 0.62
            L("Arial", 400, "normal", "Arial", false, 71, 0.81, 65, -0.8),   // 111 Arial, overlap 0.56
            L("Arial", 400, "normal", "Arial", false, 86, 0.81, 79, -0.45),   // 112 Arial, overlap 0.59
            L("Arial", 400, "normal", "Arial", false, 314, 0.67, 244, -1.17),   // 113 Arial, overlap 0.55
            L("Arial", 400, "normal", "Arial", false, 53, 0.892, 51, -0.44),   // 114 Arial, overlap 0.54
            L("Arial", 400, "normal", "Arial", false, 71, 0.842, 65, -0.35),   // 115 Arial, overlap 0.56
            L("Impact", 400, "normal", "Impact", false, 28, 1.229, 30, -0.1),   // 116 Impact, overlap 0.65
            L("Arial", 400, "normal", "Arial", false, 106, 0.816, 98, 0.0),   // 117 Arial, overlap 0.54
            L("Arial", 400, "normal", "Arial", false, 177, 0.813, 163, -0.46),   // 118 Arial, overlap 0.54
            L("Arial", 700, "normal", "Arial", true, 56, 0.86, 52, -0.38),   // 119 Arial Bold, overlap 0.70
            L("Consolas", 700, "normal", "Consolas", true, 59, 0.795, 53, 0.04),   // 120 Consolas Bold, overlap 0.67
            L("Consolas", 700, "normal", "Consolas", true, 33, 0.891, 32, -0.21),   // 121 Consolas Bold, overlap 0.69
            L("Arial", 400, "normal", "Arial", false, 67, 0.811, 62, -0.9),   // 122 Arial, overlap 0.58
            L("Arial", 400, "normal", "Arial", false, 37, 0.678, 34, -0.42),   // 123 Arial, overlap 0.61
            L("Arial", 400, "normal", "Arial", false, 48, 0.718, 45, -0.17),   // 124 Arial, overlap 0.61
            L("Arial", 400, "normal", "Arial", false, 64, 0.687, 59, -0.37),   // 125 Arial, overlap 0.55
            L("Arial", 400, "normal", "Arial", false, 57, 0.68, 53, -0.37),   // 126 Arial, overlap 0.55
            null,   // 127
        };
    }
}
